#!/bin/sh

CONF=/etc/smartdns.conf

gen_conf(){
	port=$(nvram get smartdns_port)
	[ -z "$port" ] && port=53
	cache=$(nvram get smartdns_cache)
	[ -z "$cache" ] && cache=512
	servers=$(nvram get smartdns_servers)
	speed_check=$(nvram get smartdns_speed_check)
	dualstack=$(nvram get smartdns_dualstack)
	ttl_min=$(nvram get smartdns_ttl_min)

	echo "# generated by smartdns.sh" > $CONF
	echo "server-name smartdns" >> $CONF
	echo "bind 127.0.0.1:$port" >> $CONF
	echo "bind-tcp 127.0.0.1:$port" >> $CONF
	lan=$(nvram get lan_ipaddr)
	if [ -n "$lan" ]; then
		echo "bind $lan:$port" >> $CONF
		echo "bind-tcp $lan:$port" >> $CONF
	fi
	echo "hosts-file /etc/hosts" >> $CONF
	echo "cache-size $cache" >> $CONF
	echo "prefetch-domain yes" >> $CONF
	echo "serve-expired yes" >> $CONF
	if [ -n "$speed_check" ] && [ "$speed_check" != "none" ]; then
		case "$speed_check" in
			*udp*) logger -st "smartdns" "skip invalid speed-check-mode: $speed_check"; speed_check="" ;;
		esac
		[ -n "$speed_check" ] && echo "speed-check-mode $speed_check" >> $CONF
	fi
	if [ "$dualstack" = "1" ]; then
		echo "dualstack-ip-selection yes" >> $CONF
	fi
	if [ -n "$ttl_min" ] && [ "$ttl_min" != "0" ]; then
		echo "rr-ttl-min $ttl_min" >> $CONF
	fi
	for s in $servers; do
		[ -z "$s" ] && continue
		case "$s" in
			*\|*) t=${s%%|*}; a=${s#*|} ;;
			*)    t=udp; a=$s ;;
		esac
		case "$t" in
			tcp)   echo "server $a -tcp" >> $CONF ;;
			tls)   echo "server-tls $a" >> $CONF ;;
			https) echo "server-https $a" >> $CONF ;;
			*)     echo "server $a" >> $CONF ;;
		esac
	done
}

func_start(){
	# 重启/重复启动时先确保旧进程退出并重新生成配置，
	# 避免 restart 链路中“旧进程尚未退出即被判为已运行”而跳过启动。
	killall -q smartdns
	sleep 1
	gen_conf
	/usr/bin/smartdns -c $CONF
	sleep 1
	if pidof smartdns >/dev/null 2>&1; then
		logger -st "smartdns" "started"
	else
		logger -st "smartdns" "start failed (port busy or bad config?)"
	fi
}

func_stop(){
	killall -q smartdns
}

case "$1" in
start)
	func_start
	;;
stop)
	func_stop
	;;
restart)
	func_stop
	sleep 1
	func_start
	;;
*)
	echo "Usage: $0 { start | stop | restart }"
	exit 1
	;;
esac
