#!/bin/sh

CONF=/etc/smartdns.conf

gen_conf(){
	port=$(nvram get smartdns_port)
	[ -z "$port" ] && port=53
	cache=$(nvram get smartdns_cache)
	[ -z "$cache" ] && cache=512
	servers=$(nvram get smartdns_servers)

	echo "# generated by smartdns.sh" > $CONF
	echo "server-name smartdns" >> $CONF
	echo "bind 127.0.0.1:$port" >> $CONF
	echo "bind-tcp 127.0.0.1:$port" >> $CONF
	lan=$(nvram get lan_ipaddr)
	if [ -n "$lan" ]; then
		echo "bind $lan:$port" >> $CONF
		echo "bind-tcp $lan:$port" >> $CONF
	fi
	echo "hosts-file /etc/hosts" >> $CONF
	echo "cache-size $cache" >> $CONF
	echo "prefetch-domain yes" >> $CONF
	echo "serve-expired yes" >> $CONF
	for s in $servers; do
		echo "server $s" >> $CONF
	done
}

func_start(){
	if pidof smartdns >/dev/null 2>&1; then
		logger -st "smartdns" "already running"
		return 0
	fi
	gen_conf
	/usr/bin/smartdns -c $CONF
	sleep 1
	if pidof smartdns >/dev/null 2>&1; then
		logger -st "smartdns" "started"
	else
		logger -st "smartdns" "start failed (port busy or bad config?)"
	fi
}

func_stop(){
	killall -q smartdns
}

case "$1" in
start)
	func_start
	;;
stop)
	func_stop
	;;
restart)
	func_stop
	sleep 1
	func_start
	;;
*)
	echo "Usage: $0 { start | stop | restart }"
	exit 1
	;;
esac
